### PR TITLE
Integrating StyleSystem Classes for Component Wrapper div tags in SPA Editor - React Impl

### PR DESCRIPTION
**Pull request by friendlymahi**
## Description

Changes done to EditableComponent to support StyleSystem based on appliedCssClassNames property from Sling Model exporters. Please refer to related issue for more details.

## Related Issue

Here is the related issue requesting this feature. #68 

## Motivation and Context

These changes extend the style system capability/feature to SPA Editor implementation for React apps.

## How Has This Been Tested?

Changes done locally and deployed to AEM instance via a brand new project to confirm that stysystem works as expected. Related issue #68 has screenshots of these tests. Aditionally unit tests are also included to validate this behavior.

## Screenshots (if appropriate):

Refer to related issue.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Additional Notes

If this PR is approved/merged, the page below requires updates against limitations section where we now can support StyleSystem. Additionally we need to include documentation for using style system with examples either in the next archetype or in WKND events sample project. Additionally we need to capture the need for registering the property appliedCssClassNames against any custom sling model that needs style system capability.

### CODE REVIEW

**Comment by friendlymahi** [comment]
@vladbailescu , @sharanyavinod , @godanny86 - Requesting your review and feedback. Related issue has all details you may need for reviewing this PR. Thank you so much !!

**Comment by niekraaijmakers** [comment]
LGTM. Actually really smart to make it work across all components in 1 swoop. 

Just curious, is the style system supposed to have this css class applied on the parent and not the same component? I can't say I actually used the style system so can't tell.

Seems to work fine though.

**Comment by friendlymahi** [comment]
> LGTM. Actually really smart to make it work across all components in 1 swoop.
> 
> Just curious, is the style system supposed to have this css class applied on the parent and not the same component? I can't say I actually used the style system so can't tell.
> 
> Seems to work fine though.

Great question. A while back me and @vladbailescu had a conversation on the same. 

When you adjust a layout of a component, the layout info is indeed stored at the component level. However this data (columnClassNames) is exported as part of the parent responsive grid and not the individual comp as the class info makes sense only in the context of responsive grid. And when rendering HTL, data-sly-resource implementation is done in such a way that both layout classes and applied at the parent level.

For actual components, the idea is the applied classes should be exported within the same json exporter and not the parent component, as these classes have no relation with layout classes. And the implementation is done accordingly in WCM Core Components git repo. And why is this important - coz the child component wil re-render with new styles only if the incoming props are updated. Including the style classes in parent component may force a reload on the parent container which perhaps is not the best experience.

**Comment by niekraaijmakers** [comment]
Well I lack rights to merge / review, but you have my seal of approval :)

**Comment by friendlymahi** [comment]
@habansal , @CezCz , @sharanyavinod - Please feel free to add your comments and advise on the next course of actions. Thank you !

**Review by CezCz — APPROVED** [review]

**Comment by friendlymahi** [comment]
@CezCz - Thank you so much for approving the PR. Can you please advise on the next steps? How we can get this merged and included into the next version, and additionally updates to SPA Editor documentation as well as CHANGELOG on support for this feature.

**Comment by CezCz** [comment]
@friendlymahi thanks for the contribution. We have a semantic release bot running, which releases things automatically. I forgot to format your commit appropriately and just committed an empty one. It should trigger the release which and changelog and so on.
I'd be grateful if you created an issue for angular editable components.

**Comment by friendlymahi** [comment]
@CezCz - As requested, created an [issue # 60 for Angular SPAs to support StyleSystem](https://github.com/adobe/aem-angular-editable-components/issues/60). I never worked on Angular to contribute over there, probably need other volunteers/contributors.

@niekraaijmakers

**Comment by friendlymahi** [comment]
> @friendlymahi thanks for the contribution. We have a semantic release bot running, which releases things automatically. I forgot to format your commit appropriately and just committed an empty one. It should trigger the release which and changelog and so on.
> I'd be grateful if you created an issue for angular editable components.

Thanks for your response. If there are no more checks, please close the [issue # 68 - [feature] StyleSystem Impl for React SPAs that leverage SPA Editor](https://github.com/adobe/aem-react-editable-components/issues/68)

**Pull request merged**
