### PR TITLE
feat(Container): Export childComponents as array. Fixes issue #189

### PR DESCRIPTION
**Pull request by friendlymahi**
## Description

SPA 2.0 Impl refactored all existing class based comps to functional comps. In the process the ability to obtain child components in custom components like tabs, accordion and carousel are lost as the default markup generated by container or responsivegrid components doesnt fit the need. This PR addresses this issue by decoupling the logic to consolidate all children into an array via a utility method and calling the same in Container's render. Now the utility method is exported as well so consumers can continue to use similar logic as we did before SPA 2.0

## Related Issue
#189 

## Motivation and Context
Explained in description and reported issue.

## How Has This Been Tested?

We were able to rebuild tabs component using the changes suggested. Also the OOTB container and Responsivegrid components also worked as desired.

## Screenshots (if appropriate):
If needed I can build a sample and attach screenshots. As the React Core Comps SPA repo is not migrated to SPA 2.0 we dont have an easy way to share the issue in a generic codebase like WKND SPA.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Addl unit tests are not included as the existing tests cover this method. If desired, we can add them on request from approvers.

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by friendlymahi** [comment]
@sharanyavinod , @CezCz , @niekraaijmakers , @habansal , @vladbailescu - Requesting your inputs on this PR, as this helps consumers to build custom containers without having to duplicate the code. Thanks !

**Comment by friendlymahi** [comment]
Hello. Good Morning to you ! Can someone please share some feedback on this PR? Thanks !

**Comment by friendlymahi** [comment]
Hello. Good Morning to you ! Can someone please share some feedback on this PR? Thanks !

**Comment by friendlymahi** [comment]
@sharanyavinod - Added additional tests and minor updates. Codecov passed all checks, however SonarCloud says not enough coverage even though the tests covered all the lines. Validated in codecov and jest coverage reports. Please let me know if I am missing something here. Also I didn't bump the version in package.json assuming some one from Adobe determines when the changes should go live. Please let me know for more feedback. Also there is another PR for stylesystem support. Please take a look at that one too. Thanks

**Comment by friendlymahi** [comment]
@sharanyavinod - Just a quick followup if everything is okay or if more edits are required. Thanks

**Comment by friendlymahi** [comment]
@sharanyavinod - Please conclude your approval and merge process on this one too, so both the PRs can be part of next release. Thanks

**Comment by friendlymahi** [comment]
Hello. Hope you are doing well. Any update on this? Thanks

**Review by sharanyavinod — APPROVED** [review]
Looks good, thanks for the contribution! :)

**Comment by sharanyavinod** [comment]
@friendlymahi To trigger release, the commit needs to follow commit message conventions as mentioned at https://github.com/adobe/aem-react-editable-components#releasing. Could you please add an appropriate commit here so that release will be triggered on merge? It could also be an empty commit.

**Comment by friendlymahi** [comment]
@sharanyavinod - Added documentation on the utility method and updated commit in the format recommended. Please merge the PR if this is good.

**Comment by friendlymahi** [comment]
@sharanyavinod - Good day to you. Can you please help moving this PR for merge and release process if everything looks fine? Thanks

**Comment by friendlymahi** [comment]
@sharanyavinod - I updated the PR title also to match with commit message format. Can you see if these changes help trigger a build? Thanks

**Comment by friendlymahi** [comment]
@sharanyavinod - Any update or feedback? Thank you

**Comment by sharanyavinod** [comment]
@friendlymahi I see you added a commit with `feature:` but to trigger a release it needs to either be `feat: <msg>` or `fix: <msg>`.Could you please add a corresponding commit? Once done I can immediately merge and the changes should be released as well.

**Comment by friendlymahi** [comment]
@sharanyavinod - Updated README with sample snippets and added commit message in the format you suggested. Apologies for the confusion. Thanks !

**Comment by sharanyavinod** [comment]
@friendlymahi Done. All your changes should now be included in v2.1.0

Thanks again for the contribution! :)

**Comment by friendlymahi** [comment]
Thanks a ton @sharanyavinod for the encouragement and support. 

FYI - I see the docs generation step failed in GH actions, but able to download the latest pkg.

**Comment by sarath540** [comment]
> Hello. Good Morning to you ! Can someone please share some feedback on this PR? Thanks !

Hi I am facing this issue container.getChildren not a function

**Comment by sarath540** [comment]
Below issue i am facing can any one help on this
image
here is the code
const MyTabs = (props) => { 
 const tabItemsInOrder = Container.getChildComponents(props);
  const tabItemsJsx = tabItemsInOrder.map((tabItemJsx) =><div className="tab-item">{tabItemJsx}</div>);
  return <div className="tabs neom-tabs-section">{tabItemsJsx}</div>;

}

**Comment by friendlymahi** [comment]
@sarath540 - The method is not a class method i.e. you can directly import the getChildComponents method from @adobe/aem-react-editable-components instead of doing a Container.getChildComponents. Take a look at the test case on how the import is done. If documentation is incorrect it needs a fix. Thanks !

**Comment by friendlymahi** [comment]
You may have to troubleshoot it your self. Spa core components is more of a reference and is not directly supported by Adobe and the developer who worked on it is no longer working or supporting it. May be you can ask this question on that repo. However there are multiple catches here. Spa core components uses v1.x of react editable components which is different than 2.x that we are referring. Another thing is, panel switcher works based the selectors associated with every child component being wrapped around with. I our case we developed our own tabs component. Hope this info helps. Thanks and I suggest questions like these should come on community as this PR has nothing to do with them.

**Pull request merged**
